name: Packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - gh/*/*/base
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop . --impure -c skaffold build
