name: Packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@v20
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: |
          nix develop \
            --accept-flake-config \
            --impure \
            -c skaffold build \
              --platform linux/amd64,linux/arm64 \
              --build-image ghcr.io/shikanime/niximgs/${{ matrix.image }}
    strategy:
      matrix:
        image:
          - jellyfin
          - mlflow
          - postgresql
          - radarr
          - redis
          - sonarr
          - syncthing
          - vaultwarden
          - whisparr
